#' regionQuantiles
#'
#' @description Calculates quantile distribution from each sample, within a region with a suspected CNV. We assume true deletions would be in the lower end of the quantile distribution and true duplications to be in the upper end of the quantile distribution. Many CNVs captured by detection pipelines will be false positives, this this is a good metric to remove obvious false positives. Lower quantile (q1) and upper quantile (q2) should be adjusted based on the number of patient samples available.
#'
#' @param MA MMultiAssayExperiment object used to store all information.
#' @param bed CNV bed files stored as dataframes. Chromosomes, Start of CNV, End of CNV, Type of CNV and some other information can be kept here. It is recomended to use the most recently generated bed file. Check print(MA) to see if bed files from other anlyses have been generated.
#' @param meancov Small cov files with meanscores included. This will be stored as metadata after being generated by SARC::regionMean.
#' @param q1 Lower quantile cut-off. Default is .05. This should be adjusted based on the number of samples, i.e. less samples > higher the lower threshold.
#' @param q2 Upper quantile cut-off. Default is .95. This should be adjusted based on the number of samples, i.e. less samples > lower the higher threshold.
#'
#' @return A new bed file with two new columns. For deletions the Qlow columns will be 0 or 1, and for duplications the Qhigh columns will be 0 or 1.
#' @export
#' @import tidyverse
#' @importFrom stats quantile
#' @examples
#' data("test_bed")
#' data("test_cov")
#' SARC <- regionSet(bed = test_bed, cov = test_cov)
#' SARC <- regionSplit(MA = SARC, bed = test_bed, cov = test_cov,
#'                     startlist = metadata(SARC)[[1]],
#'                     endlist = metadata(SARC)[[2]])
#' SARC <- regionMean(MA = SARC, bed = test_bed, splitcov = metadata(SARC)[[3]])
#' SARC <- regionQuantiles(MA = SARC, bed = experiments(SARC)[[1]],
#'                       meancov = metadata(SARC)[[4]], q1=.15, q2=.85)
regionQuantiles <- function(MA, bed, meancov, q1=.05, q2=.95){

  if (missing(MA)) stop('MA is missing. Add a MultiAssayExperiment object to store data efficiently.')

  if (missing(bed)) stop('bed is missing. Add bed dataframe. Ideally the most recently created bed file should be used.')

  if (missing(meancov)) stop('meancov is missing. Add list of smaller cov dataframes which have had means calculated. Will be created from SARC::regionMean')

  #create new columns in bed file

  bed$Qlow <- ""

  bed$Qhigh <- ""

  lowerq <- list()
  higherq <- list()

  #find which samples with a deletion have a low mean value of reads

  lowerq <- lapply(meancov, function(x){

    y <- x[5:ncol(x)]

    #replace 0s with low number to avoid error

    y <- as.data.frame(replace(y, y==0, 0.001))

    y <- as.matrix(y)

    l <- nrow(y)

    q <- as.numeric(quantile(y[l,], probs = c(q1, q2)))

    r <- as.numeric(y[nrow(y),])

    ylow <- which(r <= q[1])

    xlow <- colnames(y[,ylow])

    return(xlow)

  })

  #find which samples with a detected duplication has a particularly high region mean

  higherq <- lapply(meancov, function(x){

    y <- x[5:ncol(x)]

    #replace 0s with low number to avoid error

    y <- as.data.frame(replace(y, y==0, 0.001))

    y <- as.matrix(y)

    l <- nrow(y)

    q <- as.numeric(quantile(y[l,], probs = c(q1, q2)))

    r <- as.numeric(y[nrow(y),])

    yhigh <- which(r >= q[2])

    xhigh <- colnames(y[,yhigh])

    return(xhigh)

  })

  #add 1 or 0 if the sample with the CNV was identified on either end of the distribution

  for (i in seq_len(nrow(bed))) {

    if (isTRUE(bed$TYPE[i] == "DEL")) {

      if (bed$SAMPLE[i] %in% lowerq[[i]]) {

        bed$Qlow[i] <- 1

      } else {bed$Qlow[i] <- 0}

    }

    if (isTRUE(bed$TYPE[i] == "DUP")) {

      if (bed$SAMPLE[i] %in% higherq[[i]]) {

        bed$Qhigh[i] <- 1

      } else {bed$Qhigh[i] <- 0}

    }

  }

  #add new bed file to MA

  MA2 <- suppressWarnings(suppressMessages(MultiAssayExperiment(list(BEDQUANTILE = bed))))

  #add lists of quantiles

  metadata(MA)[["LOWERQAUNTILE"]] <- lowerq

  metadata(MA)[["UPPERQAUNTILE"]] <- higherq

  MA <- suppressWarnings(c(MA, MA2))

  #return a new MA object

  return(MA)
}
