#' regionQuantiles
#'
#' @description Calculates quantile distribution from each sample, within a region with a suspected CNV. We assume true deletions would be in the lower end of the quantile distribution and true duplications to be in the upper end of the quantile distribution. Many CNVs captured by detection pipelines will be false positives, this this is a good metric to remove obvious false positives. Lower quantile (q1) and upper quantile (q2) should be adjusted based on the number of patient samples available.
#'
#' @param RE RaggedExperiment object used to store all information.
#' @param cnv List of CNVs in a dataframe containing CNVs from detection algorithms/ pipelines. It is recommended to use the most recently generated cnv file. Check print(RE) to see if cnv files from other analyses have been generated.
#' @param meancov Small cov files with meanscores included. This will be stored as metadata after being generated by SARC::regionMean.
#' @param q1 Lower quantile cut-off. Default is .05. This should be adjusted based on the number of samples, i.e. less samples > higher the lower threshold.
#' @param q2 Upper quantile cut-off. Default is .95. This should be adjusted based on the number of samples, i.e. less samples > lower the higher threshold.
#' @param nameofnewdf Name of new dataframe to be saved in metadata(RE)[['CNVlist']]. Default is CNVquantiles.
#'
#' @return A new cnv file with two new columns. For deletions the Qlow columns will be 0 or 1, and for duplications the Qhigh columns will be 0 or 1.
#' @export
#' @import tidyverse
#' @importFrom stats quantile
#' @examples
#' data("test_cnv")
#' data("test_cov")
#' SARC <- regionSet(cnv = test_cnv, cov = test_cov)
#' SARC <- regionSplit(RE = SARC, cnv = metadata(SARC)[['CNVlist']][[1]],
#'                     startlist = metadata(SARC)[[2]],
#'                     endlist = metadata(SARC)[[3]])
#' SARC <- regionMean(RE = SARC, cnv = metadata(SARC)[['CNVlist']][[1]],
#'                    splitcov = metadata(SARC)[[4]])
#' SARC <- regionQuantiles(RE = SARC, cnv = metadata(SARC)[['CNVlist']][[2]],
#'                       meancov = metadata(SARC)[[5]], q1=.1, q2=.9)
regionQuantiles <- function(RE, cnv, meancov, q1=.05, q2=.95 , nameofnewdf="CNVquantiles"){

  if (missing(RE)) stop('RE is missing. Add a RaggedExperiment object to store data efficiently.')

  if (missing(cnv)) stop('cnv is missing. Add cnv dataframe. Ideally the most recently created cnv file should be used.')

  if (missing(meancov)) stop('meancov is missing. Add list of smaller cov dataframes which have had means calculated. Will be created from SARC::regionMean')

  #create new columns in cnv file

  cnv$Qlow <- ""

  cnv$Qhigh <- ""

  lowerq <- list()

  higherq <- list()

  #find which samples with a deletion have a low mean value of reads

  lowerq <- lapply(meancov, function(x){

    y <- as.data.frame(x)
    y$ID <- NULL

    #replace 0s with low number to avoid error

    y <- as.data.frame(replace(y, y==0, 0.001))

    y <- as.matrix(y)

    l <- nrow(y)

    q <- as.numeric(quantile(y[l,], probs = c(q1, q2)))

    r <- as.numeric(y[nrow(y),])

    ylow <- which(r <= q[1])

    xlow <- colnames(y[,ylow])

    return(xlow)

  })

  #find which samples with a detected duplication has a particularly high region mean

  higherq <- lapply(meancov, function(x){

    y <- as.data.frame(x)
    y$ID <- NULL

    #replace 0s with low number to avoid error

    y <- as.data.frame(replace(y, y==0, 0.001))

    y <- as.matrix(y)

    l <- nrow(y)

    q <- as.numeric(quantile(y[l,], probs = c(q1, q2)))

    r <- as.numeric(y[nrow(y),])

    yhigh <- which(r >= q[2])

    xhigh <- colnames(y[,yhigh])

    return(xhigh)

  })

  #add 1 or 0 if the sample with the CNV was identified on either end of the distribution

  for (i in seq_len(nrow(cnv))) {

    if (isTRUE(cnv$TYPE[i] == "DEL")) {

      if (cnv$SAMPLE[i] %in% lowerq[[i]]) {

        cnv$Qlow[i] <- 1

      } else {cnv$Qlow[i] <- 0}

    }

    if (isTRUE(cnv$TYPE[i] == "DUP")) {

      if (cnv$SAMPLE[i] %in% higherq[[i]]) {

        cnv$Qhigh[i] <- 1

      } else {cnv$Qhigh[i] <- 0}

    }

  }

  #add new cnv file to RE
  metadata(RE)[["CNVlist"]][[nameofnewdf]] <- cnv

  #add lists of quantiles

  metadata(RE)[["LOWERQAUNTILE"]] <- lowerq

  metadata(RE)[["UPPERQAUNTILE"]] <- higherq

  #return a new RE object

  return(RE)
}
