#' setDPlot
#'
#' @description Quality checking plot to see the Distribution of mean scores at a given region of the genome. The sample with the suspected CNV is highlighted. Useful way of checking why a certain CNV may be a false positive.
#'
#' @param MA MultiAssayExperiment object used to store all information.
#' @param meancov Small cov files with mean scores included. This will be stored as metadata after being generated by SARC::regionMean.
#'
#' @return A list of dataframes. Each dataframe contains ranked meanscores for each sample. One dataframe is made for each CNV in the bed file.
#' @export
#'
#' @examples
#' data("test_bed")
#' data("test_cov")
#' SARC <- regionSet(bed = test_bed, cov = test_cov)
#' SARC <- regionSplit(MA = SARC, bed = test_bed, cov = test_cov,
#'                     startlist = metadata(SARC)[[1]],
#'                     endlist = metadata(SARC)[[2]])
#' SARC <- regionMean(MA = SARC, bed = test_bed, splitcov = metadata(SARC)[[3]])
#' SARC <- regionQuantiles(MA = SARC, bed = experiments(SARC)[[1]],
#'                         meancov = metadata(SARC)[[3]], q1 =.1, q2 = .9)
#' SARC <- setQDplot(MA = SARC, meancov = metadata(SARC)[[4]])
setQDplot <- function(MA, meancov){

  if (missing(MA)) stop('MA is missing. Add a MultiAssayExperiment object to store data efficiently.')

  if (missing(meancov)) stop('meancov is missing. Add list of smaller cov dataframes which have had means calculated. Will be created from SARC::regionMean')

  #re-organise the meancov dataframes for plotting by seeDist

  meanList <- lapply(meancov, function(x){

    df <- as.data.frame(t(x[nrow(x),]))

    df <- cbind(df, rownames(df))

    colnames(df) <- c("MEANSCORE", "SAMPLE")

    df <- df[order(df$MEANSCORE, decreasing = FALSE),]

    df$RANK <- seq(1,nrow(df))

    return(df)

  })

  #store in metadata

  metadata(MA)[["meanDistList"]] <- meanList

  #return new MA object

  return(MA)
}
