#' setQDPlot
#'
#' @description Quality checking plot to see the Distribution of mean scores at a given region of the genome. The sample with the suspected CNV is highlighted. Useful way of checking why a certain CNV may be a false positive.
#'
#' @param RE RaggedExperiment object used to store all information.
#' @param meancov Small cov files with mean scores included. This will be stored as metadata after being generated by SARC::regionMean.
#'
#' @return A list of dataframes. Each dataframe contains ranked meanscores for each sample. One dataframe is made for each CNV in the cnv file.
#' @export
#'
#' @examples
#' data("test_cnv")
#' data("test_cov")
#' SARC <- regionSet(cnv = test_cnv, cov = test_cov)
#' SARC <- regionSplit(RE = SARC, cnv = metadata(SARC)[[1]][[1]],
#'                     startlist = metadata(SARC)[[2]],
#'                     endlist = metadata(SARC)[[3]])
#' SARC <- regionMean(RE = SARC, cnv = metadata(SARC)[[1]][[1]],
#'                    splitcov = metadata(SARC)[[4]])
#' SARC <- setQDplot(RE = SARC, meancov = metadata(SARC)[[5]])
setQDplot <- function(RE, meancov){

  if (missing(RE)) stop('RE is missing. Add a RaggedExperiment object to store data efficiently.')

  if (missing(meancov)) stop('meancov is missing. Add list of smaller cov dataframes which have had means calculated. Will be created from SARC::regionMean')

  #re-organise the meancov dataframes for plotting by seeDist

  meanList <- lapply(meancov, function(x){

    df <- as.data.frame(t(x[nrow(x),]))

    df <- cbind(df, rownames(df))

    colnames(df) <- c("MEANSCORE", "SAMPLE")

    df <- df[order(df$MEANSCORE, decreasing = FALSE),]

    df$RANK <- seq(1,nrow(df))

    return(df)

  })

  #store in metadata

  metadata(RE)[["meanDistList"]] <- meanList

  #return new RE object

  return(RE)
}
